
artifactory:
  license:
    secret: ###ZARF_VAR_LICENSE_SECRET_NAME###
    dataKey: ###ZARF_VAR_LICENSE_SECRET_KEY###
database:
  type: postgresql
  driver: org.postgresql.Driver
  secrets:
    password:
      name: artifactory-postgres
      key: password
    user:
      name: artifactory-postgres
      key: user
    url:
      name: artifactory-postgres
      key: url
nginx:
  enabled: false
postgresql:
  enabled: false
artifactory-ha:
  enabled: false
distribution:
  enabled: false
insight:
  enabled: false
pipelines:
  enabled: false
pdnServer:
  enabled: false
redis:
  enabled: false
rabbitmq:
  enabled: false
xray:
  enabled: false
