apiVersion: v1
kind: Secret
metadata:
  name: artifactory-admin-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- $previous := lookup "v1" "Secret" .Release.Namespace "artifactory-admin-credentials" }}
{{- $randPass := (randAlphaNum 16) }}
data:
  {{- if $previous }}
  adminCreds: {{ $previous.data.adminCreds }}
  username: {{ $previous.data.username }}
  password: {{ $previous.data.password }}
  {{- else }}
  adminCreds: {{ (printf "%s@%s=%s" .Values.admin.username .Values.admin.ip $randPass) | b64enc }}
  username: {{ .Values.admin.username | b64enc }}
  password: {{ $randPass | b64enc }}
  {{- end }}
