# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v1
kind: Secret
metadata:
  name: artifactory-postgres-db
  namespace: artifactory
type: kubernetes.io/opaque
stringData:
  password: |-
    {{- $secret := "" }}
    {{- if and .Values.postgres.existingSecret.name (eq .Values.postgres.password "") }}
    {{- $secret = (lookup "v1" "Secret" .Release.Namespace .Values.postgres.existingSecret.name) }}
    {{- end }}
    {{- if $secret }}
    {{- $password := index $secret.data .Values.postgres.existingSecret.passwordKey | b64dec }}
    {{ $password }}
    {{- else }}
    {{ .Values.postgres.password }}
    {{- end }}

  url: "jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.dbName }}?{{ .Values.postgres.connectionOptions }}"
  user: "{{ .Values.postgres.username }}"
