apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: artifactory-metrics
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - path: /artifactory/api/v1/metrics
    port: http-router
    scheme: https
    basicAuth:
      password:
        name: {{ .Values.serviceMonitor.secretName }}
        key: {{ .Values.serviceMonitor.passwordKey }}
      username:
        name: {{ .Values.serviceMonitor.secretName }}
        key: {{ .Values.serviceMonitor.usernameKey }}
  selector:
    matchLabels:
      app: artifactory
