apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: artifactory
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.sso }}
  sso:
    - name: Artifactory Login
      clientId: uds-package-artifactory
      redirectUris:
        - "https://artifactory.{{ .Values.domain }}/artifactory/"
  {{- end }}
  network:
    expose:
      - service: artifactory
        podLabels:
          app: artifactory
        gateway: tenant
        host: artifactory
        port: 8082
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Ingress
        selector:
          app: artifactory
        remoteNamespace: monitoring
        remoteSelector:
          app.kubernetes.io/name: prometheus
        ports:
          - 8082
        description: "Prometheus Metrics"

      - direction: Egress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteGenerated: Anywhere
        podLabels:
          app: artifactory
        port: 443
        description: "SSO"

      - direction: Egress
        remoteGenerated: KubeAPI

      - direction: Egress
        selector:
          app: artifactory
        {{- if .Values.postgres.internal }}
        remoteNamespace: {{ .Values.postgres.namespace | quote }}
        remoteSelector:
          {{ .Values.postgres.selector | toYaml | nindent 10 }}
        {{- else }}
        port: {{ .Values.postgres.port }}
        remoteGenerated: Anywhere
        {{- end }}
        description: "Postgres"

      # Custom rules for unanticipated scenarios
      {{- range .Values.customNetworkPolicies }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
      {{- end }}
