variables:
  - name: FLAVOR
    default: "registry1"

tasks:
  - name: artifactory-test-bundle
    description: Create the UDS bundle with Artifactory and its dependencies
    actions:
      - task: artifactory-package
      - task: dependency-package
      - cmd: uds create bundle --confirm --no-progress --architecture=${UDS_ARCH}

  - name: artifactory-package
    description: Create the UDS Artifactory Zarf Package
    actions:
      - cmd: zarf package create --confirm --no-progress --architecture=${ZARF_ARCHITECTURE} --flavor ${FLAVOR}

  - name: dependency-package
    description: Create the Dependency Zarf Package(s)
    actions:
      - cmd: |
          zarf package create src/dev-secrets/ --confirm --no-progress --architecture=${UDS_ARCH} --skip-sbom
