tasks:
  - name: artifactory-package
    actions:
      - description: Deploy the UDS Artifactory Zarf Package
        cmd: zarf package deploy zarf-package-artifactory-${UDS_ARCH}-*.tar.zst --confirm --no-progress

  - name: artifactory-test-bundle
    actions:
      - description: Deploy the UDS bundle with Artifactory and its dependencies
        cmd: UDS_CONFIG=bundle/uds-config.yaml uds deploy bundle/uds-bundle-artifactory-test-${UDS_ARCH}-*.tar.zst --confirm --no-progress
