# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: health-check
    actions:
      - description: Artifactory StatefulSet Health Check
        wait:
          cluster:
            kind: StatefulSet
            name: artifactory
            namespace: artifactory

  - name: ingress
    actions:
      - description: Artifactory UI Health Check
        wait:
          network:
            protocol: https
            address: artifactory.uds.dev/ui/login/
            code: 200

  - name: all
    actions:
      - task: test:health-check
      - task: test:ingress
      - task: test:credentials
      - task: test:ui

  - name: ui
    description: Artifactory UI Checks
    actions:
      - dir: tests
        cmd: |
          docker run --user="$(id -u)" --rm --ipc=host --net=host --mount type=bind,source="$(pwd)",target=/app mcr.microsoft.com/playwright:v1.53.0-jammy sh -c " \
            export npm_config_cache=/tmp/.npm && \
            cd app && \
            npm ci && \
            npx playwright test \
            "

  - name: credentials
    actions:
      - description: Gets the randomly generated password to test login
        cmd: echo "PASSWORD=$(./uds zarf tools kubectl get secrets artifactory-admin-credentials -n artifactory -o=jsonpath='{.data.password}' | base64 -d)" > tests/.env
