# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v1
kind: Secret
metadata:
  name: artifactory-postgres
  namespace: artifactory
type: kubernetes.io/opaque
stringData:
  password: "###ZARF_VAR_POSTGRES_DB_PASSWORD###"
  url: "jdbc:postgresql://###ZARF_VAR_ARTIFACTORY_DB_ENDPOINT###:5432/###ZARF_VAR_ARTIFACTORY_DB_NAME###?sslfactory=org.postgresql.ssl.NonValidatingFactory&sslmode=require"
  user: "###ZARF_VAR_ARTIFACTORY_DB_USERNAME###"
