# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

variables:
  artifactory:
    ARTIFACTORY_DB_ENDPOINT: "pg-cluster.postgres.svc.cluster.local"
    ARTIFACTORY_DB_USERNAME: "artifactory.artifactory"
  postgres-operator:
    postgresql:
      enabled: true  # Set to false to not create the PostgreSQL resource
      teamId: "uds"
      volume:
        size: "10Gi"
      numberOfInstances: 2
      users:
        artifactory.artifactory: []  # database owner
      databases:
        artifactorydb: artifactory.artifactory
      version: "13"
      ingress:
        remoteGenerated: Anywhere
