name: Test

# This workflow is triggered on pull requests to the main branch.
on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - ".gitignore"
      - "renovate.json"
      - ".release-please-config.json"
      - "release-please-config.json"
      - "oscal-component.yaml"
      - "CODEOWNERS"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "SECURITY.md"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-test:
    name: ${{ matrix.type }} ${{ matrix.flavor }}
    runs-on: uds-ubuntu-big-boy-8-core
    timeout-minutes: 25
    strategy:
      matrix:
        flavor: [registry1]
        type: [install]
        # Cannot test upgrade without a license key
        # type: [install, upgrade]

    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@11e591f2ec7d158923d973c85097ce28a5f55db4 # v0.4.5
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        uses: defenseunicorns/uds-common/.github/actions/test@11e591f2ec7d158923d973c85097ce28a5f55db4 # v0.4.5
        with:
          flavor: ${{ matrix.flavor }}
          type: ${{ matrix.type }}

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@11e591f2ec7d158923d973c85097ce28a5f55db4 # v0.4.5
        with:
          suffix: ${{ matrix.type }}-${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Print cluster info
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl get nodes -o wide

      - name: Print pod info
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl get pods -A -o wide

      - name: Print service info
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl get svc -A -o wide

      - name: Print events
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl get events -A -o wide
